# Generated by Django migration for SebaCox Category & Service Engine
import django.db.models.deletion
from django.db import migrations, models
import apps.categories.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(db_index=True, max_length=150)),
                ('name_en', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True, validators=[apps.categories.validators.validate_slug])),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('description_bn', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('level', models.PositiveIntegerField(db_index=True, default=0)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('kind', models.CharField(choices=[('PUBLIC_SERVICE_CATEGORY', 'পাবলিক সেবা ক্যাটাগরি (Public Service Category)'), ('SYSTEM_DOMAIN', 'সিস্টেম ডোমেন (System Domain)')], db_index=True, default='PUBLIC_SERVICE_CATEGORY', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name': 'ক্যাটাগরি (Category)',
                'verbose_name_plural': 'ক্যাটাগরিসমূহ (Categories)',
                'ordering': ['sort_order', 'name_bn'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(db_index=True, max_length=150)),
                ('name_en', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True, validators=[apps.categories.validators.validate_slug])),
                ('short_description_bn', models.TextField(blank=True, default='')),
                ('short_description_en', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('service_type', models.CharField(choices=[('SERVICE', 'সাধারণ সেবা (Service)'), ('PRODUCT', 'পণ্য / সামগ্রী (Product)'), ('RENTAL', 'ভাড়া সেবা (Rental)'), ('BOOKING', 'বুকিং / অ্যাপয়েন্টমেন্ট (Booking)'), ('DIGITAL_SERVICE', 'ডিজিটাল সেবা (Digital Service)'), ('INFORMATION', 'তথ্যমূলক সেবা (Information)'), ('MARKETPLACE', 'মার্কেটপ্লেস লেনদেন (Marketplace)')], db_index=True, default='SERVICE', max_length=30)),
                ('requires_booking', models.BooleanField(db_index=True, default=False)),
                ('supports_demand', models.BooleanField(db_index=True, default=False)),
                ('supports_offer', models.BooleanField(db_index=True, default=False)),
                ('supports_negotiation', models.BooleanField(db_index=True, default=False)),
                ('supports_delivery', models.BooleanField(db_index=True, default=False)),
                ('supports_location', models.BooleanField(db_index=True, default=True)),
                ('supports_online', models.BooleanField(db_index=True, default=False)),
                ('supports_order', models.BooleanField(db_index=True, default=False)),
                ('supports_rental', models.BooleanField(db_index=True, default=False)),
                ('supports_payment', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='categories.category')),
                ('secondary_categories', models.ManyToManyField(blank=True, related_name='cross_services', to='categories.category')),
            ],
            options={
                'verbose_name': 'সেবা (Service)',
                'verbose_name_plural': 'সেবাসমূহ (Services)',
                'ordering': ['sort_order', 'name_bn'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'kind', 'parent', 'sort_order'], name='categories__is_acti_4d1734_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured', 'is_active'], name='categories__is_feat_0295da_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active', 'sort_order'], name='categories__categor_594191_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_featured', 'is_active'], name='categories__is_feat_320392_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type', 'is_active'], name='categories__service_201d15_idx'),
        ),
    ]
