# Generated by Django migration for SebaCox Master Taxonomy v1.0
import django.db.models.deletion
from django.db import migrations, models
import apps.categories.validators


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        # Add is_popular to Category
        migrations.AddField(
            model_name='category',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False, help_text='জনপ্রিয় ক্যাটাগরি হাইলাইট'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_popular', 'is_active'], name='categories__is_popu_0494be_idx'),
        ),

        # Create SubCategory Model
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(db_index=True, help_text='সাব-ক্যাটাগরির বাংলা নাম', max_length=150)),
                ('name_en', models.CharField(db_index=True, help_text='English SubCategory Name', max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True, validators=[apps.categories.validators.validate_slug])),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('short_description_bn', models.TextField(blank=True, default='')),
                ('short_description_en', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_popular', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='প্রধান ক্যাটাগরি (Parent Master Category)', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category')),
            ],
            options={
                'verbose_name': 'সাব-ক্যাটাগরি (SubCategory)',
                'verbose_name_plural': 'সাব-ক্যাটাগরিসমূহ (SubCategories)',
                'ordering': ['sort_order', 'name_bn'],
            },
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name_bn'), name='unique_subcategory_per_category_bn'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'is_active', 'sort_order'], name='categories__categor_740c26_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['is_popular', 'is_active'], name='categories__is_popu_2ffce6_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['slug', 'is_active'], name='categories__slug_84a7e4_idx'),
        ),

        # Add subcategory FK to Service
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='সাব-ক্যাটাগরি (SubCategory classification)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='categories.subcategory'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['subcategory', 'is_active'], name='categories__subcate_e6db47_idx'),
        ),

        # Create TaxonomyAlias Model
        migrations.CreateModel(
            name='TaxonomyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(db_index=True, help_text='এলিয়াস বা বিকল্প নাম', max_length=150)),
                ('normalized_text', models.CharField(db_index=True, help_text='স্বাভাবিককৃত সার্চ টেক্সট', max_length=150)),
                ('target_type', models.CharField(choices=[('CATEGORY', 'Category'), ('SUBCATEGORY', 'SubCategory'), ('SERVICE', 'Service'), ('SKILL', 'Skill')], db_index=True, default='SUBCATEGORY', max_length=30)),
                ('target_id', models.PositiveIntegerField(db_index=True, help_text='টার্গেট অবজেক্টের আইডি')),
                ('language', models.CharField(choices=[('BN', 'Bangla'), ('EN', 'English'), ('ALL', 'All/Bilingual')], default='BN', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='categories.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='categories.subcategory')),
            ],
            options={
                'verbose_name': 'ট্যাক্সোনমি এলিয়াস (Taxonomy Alias)',
                'verbose_name_plural': 'ট্যাক্সোনমি এলিয়াসসমূহ (Taxonomy Aliases)',
            },
        ),
        migrations.AddIndex(
            model_name='taxonomyalias',
            index=models.Index(fields=['normalized_text', 'is_active'], name='categories__normali_f2ec20_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomyalias',
            index=models.Index(fields=['target_type', 'target_id'], name='categories__target__b4b574_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomyalias',
            index=models.Index(fields=['category', 'is_active'], name='categories__categor_594e95_idx'),
        ),
    ]
