# Generated by Django migration for SebaCox Master Taxonomy v1.0 Seed & Non-Destructive Migration
from django.db import migrations
from apps.categories.constants import SEBACOX_31_MASTER_CATEGORIES, INITIAL_TAXONOMY_ALIASES


def seed_master_taxonomy_v1(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    SubCategory = apps.get_model('categories', 'SubCategory')
    TaxonomyAlias = apps.get_model('categories', 'TaxonomyAlias')

    valid_master_slugs = set()
    category_obj_map = {}

    # 1. Seed / Upsert 31 Master Categories
    for cat_data in SEBACOX_31_MASTER_CATEGORIES:
        slug = cat_data['slug']
        valid_master_slugs.add(slug)

        category, _ = Category.objects.update_or_create(
            slug=slug,
            defaults={
                'name_bn': cat_data['name_bn'],
                'name_en': cat_data['name_en'],
                'icon': cat_data.get('icon', ''),
                'description_bn': cat_data.get('description_bn', ''),
                'description_en': cat_data.get('description_en', ''),
                'sort_order': cat_data['order'],
                'kind': cat_data.get('kind', 'PUBLIC_SERVICE_CATEGORY'),
                'is_active': True,
                'is_featured': cat_data.get('is_featured', False),
                'is_popular': cat_data.get('is_popular', False),
                'level': 0,
                'parent': None,
            }
        )
        category_obj_map[cat_data['id']] = category

        # 2. Seed / Upsert SubCategories
        for sub_data in cat_data.get('subcategories', []):
            sub_slug = sub_data['slug']
            SubCategory.objects.update_or_create(
                slug=sub_slug,
                defaults={
                    'category': category,
                    'name_bn': sub_data['name_bn'],
                    'name_en': sub_data['name_en'],
                    'sort_order': sub_data.get('order', 0),
                    'is_active': True,
                    'is_popular': sub_data.get('is_popular', False),
                }
            )

    # 3. Non-destructive legacy category deactivation (KEEP existing rows safe)
    # We do NOT delete any existing category to protect ForeignKey references in Demands/Providers/Services
    Category.objects.exclude(slug__in=valid_master_slugs).filter(level=0, kind='PUBLIC_SERVICE_CATEGORY').update(
        is_active=False
    )

    # 4. Seed Taxonomy Aliases
    for alias_data in INITIAL_TAXONOMY_ALIASES:
        target_cat = category_obj_map.get(alias_data.get('category_id'))
        TaxonomyAlias.objects.update_or_create(
            alias_text=alias_data['alias_text'],
            defaults={
                'normalized_text': alias_data['normalized_text'],
                'target_type': alias_data['target_type'],
                'target_id': alias_data['target_id'],
                'language': alias_data['language'],
                'category': target_cat,
                'is_active': True,
            }
        )


def reverse_seed_master_taxonomy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_master_taxonomy_v1'),
    ]

    operations = [
        migrations.RunPython(seed_master_taxonomy_v1, reverse_seed_master_taxonomy),
    ]
