# Generated by Django migration for SebaCox Search & Alias Engine (Phase 4C.9)
from django.db import migrations, models
import django.db.models.deletion


def resync_taxonomy_aliases(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    SubCategory = apps.get_model('categories', 'SubCategory')
    TaxonomyAlias = apps.get_model('categories', 'TaxonomyAlias')
    from apps.categories.constants import INITIAL_TAXONOMY_ALIASES

    cat_map = {c.id: c for c in Category.objects.all()}
    sub_map = {s.id: s for s in SubCategory.objects.all()}

    for alias_data in INITIAL_TAXONOMY_ALIASES:
        target_cat = cat_map.get(alias_data.get('category_id'))
        target_sub = None
        if alias_data.get('target_type') == 'SUBCATEGORY':
            target_sub = sub_map.get(alias_data.get('target_id'))

        TaxonomyAlias.objects.update_or_create(
            alias_text=alias_data['alias_text'],
            defaults={
                'normalized_text': alias_data['normalized_text'],
                'target_type': alias_data['target_type'],
                'target_id': alias_data['target_id'],
                'language': alias_data['language'],
                'alias_type': alias_data.get('alias_type', 'COMMON'),
                'priority': alias_data.get('priority', 100),
                'category': target_cat,
                'subcategory': target_sub,
                'is_active': True,
            }
        )


def reverse_resync_taxonomy_aliases(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_seed_master_taxonomy_v1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomyalias',
            options={
                'ordering': ['-priority', 'alias_text'],
                'verbose_name': 'ট্যাক্সোনমি এলিয়াস (Taxonomy Alias)',
                'verbose_name_plural': 'ট্যাক্সোনমি এলিয়াসসমূহ (Taxonomy Aliases)',
            },
        ),
        migrations.AddField(
            model_name='taxonomyalias',
            name='alias_type',
            field=models.CharField(
                choices=[
                    ('EXACT', 'সঠিক প্রতিশব্দ (Exact Match)'),
                    ('COMMON', 'বহুল প্রচলিত শব্দ (Common Term)'),
                    ('COLLOQUIAL', 'স্থানীয় ও কথ্য ভাষা (Colloquial / Vernacular)'),
                    ('SPELLING_VARIANT', 'বানান রূপভেদ (Spelling Variant)'),
                    ('BANGLA', 'বাংলা প্রতিশব্দ (Bangla Synonym)'),
                    ('ENGLISH', 'ইংরেজি পরিভাষা (English Keyword)'),
                    ('ABBREVIATION', 'সংক্ষিপ্ত রূপ (Abbreviation / Acronym)'),
                    ('LOCAL_TERM', 'কক্সবাজার আঞ্চলিক শব্দ (Cox Local Term)'),
                    ('TYPO', 'সাধারণ টাইপো (Phonetic / Common Typo)'),
                ],
                db_index=True,
                default='COMMON',
                help_text='এলিয়াসের ধরণ (EXACT, COMMON, COLLOQUIAL, LOCAL_TERM, etc.)',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='taxonomyalias',
            name='priority',
            field=models.PositiveIntegerField(
                db_index=True,
                default=100,
                help_text='সার্চ প্রায়োরিটি ওয়েট (উচ্চ মান = উচ্চ স্থান)',
            ),
        ),
        migrations.AddField(
            model_name='taxonomyalias',
            name='service_type',
            field=models.CharField(
                blank=True,
                default='',
                help_text='নির্দিষ্ট সেবার ধরণ (ঐচ্ছিক)',
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name='taxonomyalias',
            index=models.Index(fields=['priority', 'is_active'], name='categories__priorit_f691b0_idx'),
        ),
        migrations.RunPython(resync_taxonomy_aliases, reverse_resync_taxonomy_aliases),
    ]
