# Generated by Django migration for SebaCox Taxonomy Governance, Versioning & Audit Trail (Phase 4D)
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def initialize_taxonomy_version_1_0(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    SubCategory = apps.get_model('categories', 'SubCategory')
    TaxonomyAlias = apps.get_model('categories', 'TaxonomyAlias')
    TaxonomyVersion = apps.get_model('categories', 'TaxonomyVersion')
    TaxonomyChangeLog = apps.get_model('categories', 'TaxonomyChangeLog')

    # Ensure Category and SubCategory status is set to ACTIVE if active
    Category.objects.filter(is_active=True, status='').update(status='ACTIVE')
    SubCategory.objects.filter(is_active=True, status='').update(status='ACTIVE')

    cat_count = Category.objects.filter(is_active=True, level=0).count()
    sub_count = SubCategory.objects.filter(is_active=True).count()
    alias_count = TaxonomyAlias.objects.filter(is_active=True).count()

    TaxonomyVersion.objects.get_or_create(
        version_number='1.0',
        defaults={
            'release_title': 'SebaCox Master Taxonomy v1.0 (Canonical 31 Categories)',
            'description': 'Official release of 31 Master Categories, granular sub-categories, and vernacular search alias engine for Cox\'s Bazar marketplace.',
            'changelog': [
                'Initial release of 31 Master Categories',
                'Integration of Provider and Demand capability matrix',
                'Vernacular and phonetic search alias engine',
                'Deterministic scoring and categorization architecture'
            ],
            'is_current': True,
            'total_categories_count': cat_count,
            'total_subcategories_count': sub_count,
            'total_aliases_count': alias_count,
            'checksum': 'sebax-tax-v1.0-master-canonical'
        }
    )


def reverse_taxonomy_version_init(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0004_search_alias_engine_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'খসড়া (Draft)'),
                    ('ACTIVE', 'সক্রিয় (Active)'),
                    ('INACTIVE', 'নিষ্ক্রিয় (Inactive)'),
                    ('DEPRECATED', 'বাতিলকৃত/অপ্রচলিত (Deprecated)'),
                    ('MERGED', 'একীভূত (Merged)')
                ],
                db_index=True,
                default='ACTIVE',
                help_text='ট্যাক্সোনমি লাইফসাইকেল স্ট্যাটাস (DRAFT, ACTIVE, INACTIVE, DEPRECATED, MERGED)',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='merged_into',
            field=models.ForeignKey(
                blank=True,
                help_text='একীভূতকৃত টার্গেট ক্যাটাগরি (Merged target category)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='merged_categories',
                to='categories.category'
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='replacement',
            field=models.ForeignKey(
                blank=True,
                help_text='প্রতিস্থাপক ক্যাটাগরি (Replacement category)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='replaced_categories',
                to='categories.category'
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='deprecation_reason',
            field=models.TextField(
                blank=True,
                default='',
                help_text='বাতিল বা অপ্রচলনের কারণ (Reason for deprecation/merger)'
            ),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['status', 'is_active'], name='categories__status_e59c0d_idx'),
        ),

        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'খসড়া (Draft)'),
                    ('ACTIVE', 'সক্রিয় (Active)'),
                    ('INACTIVE', 'নিষ্ক্রিয় (Inactive)'),
                    ('DEPRECATED', 'বাতিলকৃত/অপ্রচলিত (Deprecated)'),
                    ('MERGED', 'একীভূত (Merged)')
                ],
                db_index=True,
                default='ACTIVE',
                help_text='ট্যাক্সোনমি লাইফসাইকেল স্ট্যাটাস',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='merged_into',
            field=models.ForeignKey(
                blank=True,
                help_text='একীভূতকৃত টার্গেট সাব-ক্যাটাগরি',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='merged_subcategories',
                to='categories.subcategory'
            ),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='replacement',
            field=models.ForeignKey(
                blank=True,
                help_text='প্রতিস্থাপক সাব-ক্যাটাগরি',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='replaced_subcategories',
                to='categories.subcategory'
            ),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='deprecation_reason',
            field=models.TextField(
                blank=True,
                default='',
                help_text='বাতিল বা অপ্রচলনের কারণ'
            ),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['status', 'is_active'], name='categories__status_543ad4_idx'),
        ),

        migrations.CreateModel(
            name='TaxonomyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(db_index=True, default='1.0', help_text='ট্যাক্সোনমি ভার্সন নম্বর (e.g. 1.0, 1.1, 2.0)', max_length=20, unique=True)),
                ('release_title', models.CharField(default='SebaCox Master Taxonomy v1.0', help_text='রিলিজ টাইটেল', max_length=150)),
                ('description', models.TextField(blank=True, default='', help_text='ভার্সন বিবরণ ও পরিবর্তনের সারসংক্ষেপ')),
                ('changelog', models.JSONField(blank=True, default=list, help_text='কাঠামোগত পরিবর্তন ও রিলিজ নোটের তালিকা')),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='বর্তমান সক্রিয় ট্যাক্সোনমি ভার্সন কিনা')),
                ('total_categories_count', models.PositiveIntegerField(default=0, help_text='মোট সক্রিয় ক্যাটাগরি সংখ্যা')),
                ('total_subcategories_count', models.PositiveIntegerField(default=0, help_text='মোট সক্রিয় সাব-ক্যাটাগরি সংখ্যা')),
                ('total_aliases_count', models.PositiveIntegerField(default=0, help_text='মোট সক্রিয় এলিয়াস সংখ্যা')),
                ('checksum', models.CharField(blank=True, default='', help_text='ট্যাক্সোনমি কন্টেন্ট হ্যাশ / ই-ট্যাগ (for client cache validation)', max_length=64)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ট্যাক্সোনমি ভার্সন (Taxonomy Version)',
                'verbose_name_plural': 'ট্যাক্সোনমি ভার্সনসমূহ (Taxonomy Versions)',
                'ordering': ['-version_number'],
            },
        ),

        migrations.CreateModel(
            name='TaxonomyChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('CATEGORY', 'Category'), ('SUBCATEGORY', 'SubCategory'), ('SERVICE', 'Service'), ('SKILL', 'Skill')], db_index=True, help_text='এনটিটি টাইপ (CATEGORY, SUBCATEGORY, SERVICE, ALIAS, VERSION)', max_length=30)),
                ('target_id', models.PositiveIntegerField(db_index=True, help_text='টার্গেট অবজেক্টের আইডি')),
                ('target_name', models.CharField(blank=True, default='', help_text='অবজেক্টের নাম বা শিরোনাম', max_length=150)),
                ('action', models.CharField(choices=[('CREATE', 'তৈরি (Create)'), ('UPDATE', 'তথ্য আপডেট (Update)'), ('RENAME', 'পুনঃনামকরণ (Rename)'), ('DEACTIVATE', 'নিষ্ক্রিয়করণ (Deactivate)'), ('REACTIVATE', 'পুনরায় সক্রিয়করণ (Reactivate)'), ('DEPRECATE', 'বাতিলকরণ (Deprecate)'), ('MERGE', 'একীভূতকরণ (Merge)'), ('MOVE', 'স্থানান্তর (Move)'), ('REPLACE', 'প্রতিস্থাপন (Replace)'), ('ALIAS_ADDED', 'এলিয়াস যুক্ত (Alias Added)'), ('VERSION_BUMP', 'ভার্সন আপডেট (Version Bump)')], db_index=True, help_text='অ্যাকশন টাইপ (CREATE, RENAME, DEACTIVATE, MERGE, MOVE, etc.)', max_length=30)),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='পূর্বের মান')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='নতুন মান')),
                ('reason', models.TextField(blank=True, default='', help_text='পরিবর্তনের কারণ বা এডমিন নোট')),
                ('impact_summary', models.JSONField(blank=True, default=dict, help_text='প্রভাব বিশ্লেষণ সারসংক্ষেপ (Affected providers, demands, services)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='পরিবর্তনকারী এডমিন ব্যবহারকারী', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomy_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ট্যাক্সোনমি চেঞ্জ লগ (Taxonomy Change Log)',
                'verbose_name_plural': 'ট্যাক্সোনমি চেঞ্জ লগসমূহ (Taxonomy Change Logs)',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['target_type', 'target_id'], name='tax_chg_target_idx'),
                    models.Index(fields=['action', 'created_at'], name='tax_chg_action_idx'),
                ],
            },
        ),
        migrations.RunPython(initialize_taxonomy_version_1_0, reverse_taxonomy_version_init),
    ]
